name: Main

on:
  # on-webhook
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node_version: '16'
        cache: 'npm'
    - name: Install dependencies
      run: npm install
      # run: npm ci --ignore-scripts
    - name: Run index.js
      run: node index.js