name: Main

on:
  # on-webhook
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.branch || 'master' }}
    - name: Run index.js
      run: node index.js